[package]
name = "lottery-presentation"
version = "0.1.0"
authors = ["fteychene <francois.teychene@gmail.com>"]

[dependencies]
# Error
failure = "0.1.3"
failure_derive = "0.1.2"
# Json
serde = "1.0"
serde_derive = "1.0"
# Http client
reqwest = "0.8.1"
# Utils
frunk = "0.2.1"
rand = "0.5.5"
matches = "0.1.8"
# Actor
actix = "0.7"
actix-web = { version = "0.7", features = ["alpn"] }
tokio = "0.1.11"
# Log
log = "0.4"
env_logger = "0.5.13"
# Database code
uuid = { version = "0.5", features = ["serde", "v4"] }
diesel = { version = "^1.3.3", features = ["sqlite", "r2d2"] }
diesel_migrations= "1.1.0"
r2d2 = "0.8"